/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lendico.plangenerator.apis;

import com.lendico.plangenerator.models.LoanDetails;
import com.lendico.plangenerator.models.RepaymentPlans;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-09-06T14:21:34.595+02:00")

@Api(value = "generate-plan", description = "the generate-plan API")
public interface GeneratePlanApi {

    @ApiOperation(value = "pre-calculated repayment plans throughout the lifetime of a loan", nickname = "preCalculateRepaymentPlans", notes = "", response = RepaymentPlans.class, authorizations = {
        @Authorization(value = "BasicAuth"),
        @Authorization(value = "ClientId")
    }, tags={ "plan", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful", response = RepaymentPlans.class),
        @ApiResponse(code = 400, message = "The given input has not the right format"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 500, message = "Internal server error") })
    @RequestMapping(value = "/generate-plan",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<RepaymentPlans> preCalculateRepaymentPlans(@ApiParam(value = " Loan Details for generating pre-calculated repayment plans" ,required=true )  @Valid @RequestBody LoanDetails body);

}
