swagger: '2.0'
info:
  description: In order to inform borrowers about the final repayment schedule, thi service will doe pre-calculated repayment plans throughout the lifetime of a loan  This spec defines the ` PlanGeneratorService`. Consumers  should statisfy service contract to access the APIs.Please refer <b>request</b> and <b>response</b> section of each service to identify the contract. Also clients need to send `Basic auth` for authentication
  version: 1.0.0
  title: PlanGeneratorService
  termsOfService: http://company.io/terms/
  contact:
    email: info@company.com
host: localhost:8080
basePath: /plangeneratorservice/v1
tags:
- name: PlanGenerator
  description: Services to pre-calculate repayment plans throughout the lifetime of a loan
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: plan
  description: plan generator
schemes:
- http
- https
paths:
  /generate-plan:
    post:
      tags:
      - plan
      summary: pre-calculated repayment plans throughout the lifetime of a loan
      description: ''
      operationId: preCalculateRepaymentPlans
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - BasicAuth: [
          ]
      parameters:
      - in: body
        name: body
        description: ' Loan Details for generating pre-calculated repayment plans'
        required: true
        schema:
          $ref: '#/definitions/LoanDetails'
      responses:
        200:
          description: successful
          schema:
            $ref: '#/definitions/RepaymentPlans'
        400:
          description: The given input has not the right format
        401:
          description: Unauthorized
        500:
          description: Internal server error
securityDefinitions:
  BasicAuth:
    type: basic
definitions:
  LoanDetails:
    type: object
    properties:
      loanAmount:
        type: number
        format: double
      nominalRate:
        type: number
        format: double
      duration:
        type: integer
        format: int32
      startDate:
        type: string
        format: date-time
    required:
    - loanAmount
    - nominalRate
    - duration
    - startDate
  RepaymentPlans:
    properties:
      repaymentPlans:
        type: array
        items:
          $ref: '#/definitions/RepaymentPlan'
  RepaymentPlan:
    properties:
      borrowerPaymentAmount:
        type: number
        format: double
      date:
        type: string
        format: date-time
      initialOutstandingPrincipal:
        type: number
        format: double
      interest:
        type: number
        format: double
      principal:
        type: number
        format: double
      remainingOutstandingPrincipal:
        type: number
        format: double